/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.5.0/samples
 */


plugins {
  id("java")
  id("application")
	id("com.diffplug.spotless") version "8.1.0"
  id("org.openjfx.javafxplugin") version "0.1.0"
}

group = "donaldson.stirling"

java {
	toolchain {
		languageVersion.set(
			JavaLanguageVersion.of(21)
		)
	}
}

repositories { mavenCentral() }

application {
	mainClass.set("donaldson.stirling.App")
}

tasks.jar {
	manifest {
		attributes["Main-Class"] = "donaldson.stirling.App"
	}
}

dependencies {
	testImplementation(platform("org.junit:junit-bom:6.0.3"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

javafx {
    version = "21.0.5"
    modules = listOf("javafx.controls")
}

spotless {
	java {
		googleJavaFormat("1.28.0")
		formatAnnotations()
	}
}
